### ISSUE TITLE
URL path of SMB hidden menu?

### ISSUE THREAD

**Issue by FM1337** [gclair/Actiontec-R1000#1]
I'm curious what the URL path for the SMB hidden menu is?

**Comment by gclair** [comment]
R1000- 
advancedsetup_storagedeviceinfo.html
1sp_advancedutilities_dnscache.html
1spfwupgr0de_refresh.html
1sp_tr69.html
1sp_wanvlans_eth.html
1sp_wanvlans.html
1spfwupgr0de.html
1sp_remotetelnet.html
1sp_wanvlans_eth_hide.html 
1sp_wanvlans_eth_real.html

Unreferenced -
advancedsetup_admin.html                   advancedsetup_lanipaddress_hide.html      advancedsetup_wanipaddress.html
advancedsetup_advanceddmz.html             advancedsetup_lanipaddress_info.html      advancedsetup_websiteblocking.html
advancedsetup_advancedportforwarding.html  advancedsetup_lanipaddress_real.html      advancedutilities_dlna.html
advancedsetup_applications.html            advancedsetup_lanipdhcpsettings.html      advancedutilities_hpnadiag_reflesh.html
advancedsetup_dhcpreservation.html         advancedsetup_nat.html                    advancedutilities_igmp2.html
advancedsetup_dmzhosting.html              advancedsetup_remotegui.html              advancedutilities_ippcfg.html
advancedsetup_downstream.html              advancedsetup_schedulingaccess.html       advancedutilities_ipping.html
advancedsetup_dynamicdns.html              advancedsetup_servicesblocking.html       advancedutilities_ipping_refresh.html
advancedsetup_dynamicdns_refresh.html      advancedsetup_staticrouting.html          advancedutilities_sipalg2.html
advancedsetup_dynamicrouting.html          advancedsetup_storagedeviceinfo.html      advancedutilities_toolbox2.html
advancedsetup_firewallsettings.html        advancedsetup_storageuseraccountcfg.html  advancedutilities_traceroute.html
advancedsetup_hpna.html                    advancedsetup_upnp.html                   advancedutilities_upgradehistory2.html
advancedsetup_language.html                advancedsetup_upstream.html

R3000 - doesn't have a hidden samba menu
advancedsetup_admin.html
advancedsetup_advanceddmz.html
advancedsetup_advancedportforwarding.html
advancedsetup_applications.html
advancedsetup_dhcpreservation.html
advancedsetup_dmzhosting.html
advancedsetup_downstream.html
advancedsetup_dynamicdns.html
advancedsetup_dynamicdns_refresh.html
advancedsetup_dynamicrouting.html
advancedsetup_firewallsettings.html
advancedsetup_language.html
advancedsetup_lanipaddress_hide.html
advancedsetup_lanipaddress_info.html
advancedsetup_lanipaddress_real.html
advancedsetup_lanipdhcpsettings.html
advancedsetup_nat.html
advancedsetup_pb.html
advancedsetup_remotegui.html
advancedsetup_schedulingaccess.html
advancedsetup_servicesblocking.html
advancedsetup_staticrouting.html
advancedsetup_storagedeviceinfo.html
advancedsetup_storageuseraccountcfg.html
advancedsetup_upnp.html
advancedsetup_upstream.html
advancedsetup_wanipaddress.html
advancedsetup_websiteblocking.html
advancedutilities_alg.html
advancedutilities_arpscan.html
advancedutilities_dlna.html
advancedutilities_hpnadiag_reflesh.html
advancedutilities_ippcfg.html
advancedutilities_ipping.html
advancedutilities_ipping_refresh.html
advancedutilities_traceroute.html
advancedutilities_traceroute_refresh.html
wireless_advanced_statistics.html
wirelesssetup_advanced.html
tu1c044D_fwupgr0de.html
tu1c044D_igmp2.html
tu1c044D_policyrouting.html
tu1c044D_remotetelnet.html
tu1c044D_syslog.html
tu1c044D_toolbox2.html
tu1c044D_tr69.html
tu1c044D_wifiCounters.html
